# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources-no-clib
#
set( SOURCES_NO_CLIB
src/generate-map.c
)

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/mulle-slug.c
)
